CREATE TABLE IF NOT EXISTS TESTINGTESTING (
    id SERIAL,
    random VARCHAR(10)
);

INSERT INTO TESTINGTESTING (random) VALUES ('ohhoh5ohG4');
INSERT INTO TESTINGTESTING (random) VALUES ('Xojaitea0o');
INSERT INTO TESTINGTESTING (random) VALUES ('eeCah4Aehi');
INSERT INTO TESTINGTESTING (random) VALUES ('yo1Zee1ait');
INSERT INTO TESTINGTESTING (random) VALUES ('heek0Quaph');
INSERT INTO TESTINGTESTING (random) VALUES ('EiX2goosah');
INSERT INTO TESTINGTESTING (random) VALUES ('Iso8eiv9ca');
INSERT INTO TESTINGTESTING (random) VALUES ('miozae9ooF');
INSERT INTO TESTINGTESTING (random) VALUES ('miozae9ooF');
INSERT INTO TESTINGTESTING (random) VALUES ('ieSh7Zevah');
INSERT INTO TESTINGTESTING (random) VALUES ('HaeM2naigh');
INSERT INTO TESTINGTESTING (random) VALUES ('ieh2kah6Ru');
INSERT INTO TESTINGTESTING (random) VALUES ('Ohf7Zaethi');
INSERT INTO TESTINGTESTING (random) VALUES ('Iazie1oaCe');