---

storage:
  s3:
    endpoint:  "http://localhost:9000"
    accessKey: "minio"
    secretKey: "minio123"
    bucket:    "test"
databases:
  - host:     "localhost"
    port:     5432
    username: "postgres"
    database: "postgres"
    password: "postgres"
    retention: 30
