apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-pg-to-remote-storage
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-pg-to-remote-storage
              image: backup-pg-to-remote-storage:latest
              env:
                - name: BACKUP_PG_CONFIG_PATH
                  value: /etc/backup-pg-secret.yml
              envFrom:
                - secretRef:
                    name: backup-pg-secret.yml
              volumeMounts:
                - name: backup-pg-secret
                  mountPath: /etc/backup-pg-secret.yml
                  readOnly: true
          volumes:
            - name: backup-pg-secret
              secret:
                secretName: backup-pg-secret
