apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  s3-config: # This section defines your default s3-config. You can override this in the database section
    bucket: example
    folder: backups
    username: s3-user
    password: secret-password
    host: amazonaws.com
    region-code: eu-west
    virtual-host-style: True # Whether you use the subdomain style or (depricated) path style to access your S3-Storage
  retention: 30 # Retention-Time in days. Can be overriden in the database section 
  databases: 
    - name: example-database
      username: example-user
      password: totally-secret-password
      host: 127.0.0.1
      port: 5432
    - name: other-database
      username: other-user
      password: other-secret-password
      host: 127.0.0.1
      port: 5432
      retention: 7
      s3: #use this section to override your defaults
        bucket: other-bucket
        folder: not-backups
        username: s3-user
        password: secret-password
        host: amazonaws.com
        region-code: eu-west
        virtual-host-style: True 


  