name: build and package backup-pg-to-remote-storage

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
      - dev # just for testing

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install go dependencies
        run: make update

      - name: Install go dependencies
        run: make unittests

      - name: Build go app
        run: make build

      - name: Package go app
        run: docker build -t backup-pg-to-remote-storage .

      - name: Log in to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container image to GitHub Packages
        run: docker tag backup-pg-to-remote-storage:latest ghcr.io/garliclabs/backup-pg-to-remote-storage:latest && docker push ghcr.io/garliclabs/backup-pg-to-remote-storage:latest

      - name: Cleanup
        run: |
          docker logout ghcr.io
          rm backup-pg-to-remote-storage
          docker rmi backup-pg-to-remote-storage
